#ExtentReports Configuration
#Thu Mar 12 17:00:50 IST 2026
extent.reporter.spark.out=Reports/Run_20260312_170050/TestRun_20260312_170050.html
systeminfo.AppName=Kroviq
screenshot.dir=Reports/Run_20260312_170050/screenshots
extent.reporter.spark.start=true
extent.reporter.spark.screenshots.dir=Reports/Run_20260312_170050/screenshots
screenshot.rel.path=screenshots/
systeminfo.user=Kroviq
systeminfo.build=1.0
systeminfo.os=Windows 11
